# ==========================================
# 1. DATASOURCE (PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/poder_financeiro_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 2. HIBERNATE / JPA (Modo DEV)
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# UPDATE: O Hibernate cria e atualiza as tabelas automaticamente baseado nas entidades @Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra e formata o SQL no console para ajudar no debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# 3. CONFIGURAÇÕES DA APLICAÇÃO (JavaFX)
# ==========================================
# Desativa o servidor web embutido (Tomcat)
spring.main.web-application-type=none