# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/poder_financeiro_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desativa o Tomcat Web (já que você quer focar no JavaFX desktop)
spring.main.web-application-type=none

# Habilita o Flyway
spring.flyway.enabled=true

# Localização dos scripts (padrão do Flyway)
spring.flyway.locations=classpath:db/migration

# Permite que o Flyway limpe o banco (CUIDADO: use apenas em dev)
spring.flyway.clean-disabled=false
