-- =================================================================
-- Schema H2 para testes — ENUMs como DOMAIN sem CHECK constraint
-- =================================================================

CREATE DOMAIN IF NOT EXISTS tipo_relacionamento_enum AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS status_proposta_enum AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS origem_consentimento_enum AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS tipo_vinculo_enum AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS tipo_convenio_enum AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS uf_enum AS VARCHAR(2);
CREATE DOMAIN IF NOT EXISTS tipo_logradouro_enum AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS categoria_link_enum AS VARCHAR(50);

CREATE TABLE IF NOT EXISTS usuarios (
    usuario_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(50)  NOT NULL UNIQUE,
    nome              VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL UNIQUE,
    senha_hash        VARCHAR(255) NOT NULL,
    gemini_api_key    VARCHAR(255),
    papel             VARCHAR(50)  DEFAULT 'CONSULTOR',
    ativo             BOOLEAN      DEFAULT TRUE,
    criado_em         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    ultimo_acesso     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bancos (
    banco_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_banco         VARCHAR(10),
    nome_banco           VARCHAR(100) NOT NULL,
    link_portal_banco    TEXT,
    telefone_suporte     VARCHAR(50),
    sistema_amortizacao  VARCHAR(50)  DEFAULT 'Price',
    permite_pos_fixado   BOOLEAN      DEFAULT FALSE,
    ativo                BOOLEAN      DEFAULT TRUE,
    criado_em            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS proponentes (
    proponente_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id            BIGINT       NOT NULL,
    nome_completo         VARCHAR(255) NOT NULL,
    cpf                   VARCHAR(14)  NOT NULL,
    telefone              VARCHAR(20),
    renda_mensal          NUMERIC(12,2),
    tipo_vinculo          tipo_vinculo_enum         DEFAULT 'CLT',
    matricula             VARCHAR(50),
    origem_consentimento  origem_consentimento_enum DEFAULT 'WHATSAPP',
    classificacao         tipo_relacionamento_enum  DEFAULT 'LEAD',
    indicado_por_id       BIGINT,
    data_cadastro         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    deletado_em           TIMESTAMP,
    data_nascimento       DATE
);

CREATE TABLE IF NOT EXISTS tabelas_juros (
    tabela_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banco_id                 BIGINT        NOT NULL,
    nome_tabela              VARCHAR(100)  NOT NULL,
    taxa_mensal              NUMERIC(6,4)  NOT NULL,
    idade_minima             INTEGER       DEFAULT 18,
    idade_maxima             INTEGER       DEFAULT 100,
    renda_minima             NUMERIC(12,2) DEFAULT 0.00,
    prazo_minimo             INTEGER       DEFAULT 1,
    prazo_maximo             INTEGER       DEFAULT 96,
    valor_minimo_emprestimo  NUMERIC(12,2) DEFAULT 0.00,
    valor_maximo_emprestimo  NUMERIC(12,2) DEFAULT 999999.99,
    tipo_convenio            tipo_convenio_enum DEFAULT 'PADRAO',
    comissao_percentual      NUMERIC(5,2)  DEFAULT 0.00,
    inicio_vigencia          DATE          DEFAULT CURRENT_DATE,
    fim_vigencia             DATE,
    ativo                    BOOLEAN       DEFAULT TRUE,
    criado_em                TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS propostas (
    proposta_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proponente_id            BIGINT        NOT NULL,
    banco_id                 BIGINT        NOT NULL,
    usuario_id               BIGINT        NOT NULL,
    convenio_orgao           tipo_convenio_enum   DEFAULT 'PADRAO',
    valor_solicitado         NUMERIC(12,2) NOT NULL,
    prazo_desejado           INTEGER,
    valor_aprovado           NUMERIC(12,2),
    taxa_aplicada            NUMERIC(5,2),
    quantidade_parcelas      INTEGER,
    status                   status_proposta_enum DEFAULT 'DIGITADA',
    coeficiente              NUMERIC(10,6),
    valor_parcela            NUMERIC(12,2),
    modalidade_juros         VARCHAR(20)   DEFAULT 'Prefixado',
    custo_efetivo_total      NUMERIC(5,2),
    margem_utilizada         NUMERIC(12,2),
    eh_novacao               BOOLEAN       DEFAULT FALSE,
    saldo_quitacao_anterior  NUMERIC(12,2) DEFAULT 0.00,
    valor_iof                NUMERIC(12,2) DEFAULT 0.00,
    taxa_administracao       NUMERIC(12,2) DEFAULT 0.00,
    comissao_estimada        NUMERIC(12,2) DEFAULT 0.00,
    valor_final_cliente      NUMERIC(12,2) DEFAULT 0.00,
    data_solicitacao         DATE          DEFAULT CURRENT_DATE,
    observacoes              TEXT,
    ultima_atualizacao       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    tabela_id                BIGINT,
    usuario_atualizacao_id   BIGINT
);

CREATE TABLE IF NOT EXISTS comissoes (
    comissao_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta_id                BIGINT        NOT NULL,
    usuario_id                 BIGINT        NOT NULL,
    valor_bruto_comissao       NUMERIC(12,2) NOT NULL,
    impostos_retidos           NUMERIC(12,2) DEFAULT 0.00,
    valor_liquido_consultor    NUMERIC(12,2) NOT NULL,
    valor_pago_pela_poder      NUMERIC(12,2) DEFAULT 0.00,
    contestada                 BOOLEAN       DEFAULT FALSE,
    data_recebimento_banco     TIMESTAMP,
    verificado_consultor       BOOLEAN       DEFAULT FALSE,
    data_verificacao           TIMESTAMP,
    previsao_pagamento         DATE,
    data_pagamento_consultor   TIMESTAMP,
    status_pagamento           VARCHAR(20)   DEFAULT 'Pendente',
    ciclo_referencia           VARCHAR(10),
    data_limite_contestacao    TIMESTAMP,
    observacao_ajuste          TEXT,
    criado_em                  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documentos_proponente (
    documento_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proponente_id  BIGINT,
    proposta_id    BIGINT,
    usuario_id     BIGINT      NOT NULL,
    tipo_documento VARCHAR(50) NOT NULL,
    arquivo_path   TEXT        NOT NULL,
    hash_sha256    VARCHAR(64),
    verificado     BOOLEAN     DEFAULT FALSE,
    data_upload    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historico_status_proposta (
    historico_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta_id     BIGINT,
    usuario_id      BIGINT,
    status_anterior VARCHAR(50),
    status_novo     VARCHAR(50) NOT NULL,
    data_mudanca    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    motivo_mudanca  TEXT
);

CREATE TABLE IF NOT EXISTS interacoes_contato (
    interacao_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proponente_id  BIGINT,
    usuario_id     BIGINT      NOT NULL,
    canal          VARCHAR(20) DEFAULT 'WhatsApp',
    mensagem_texto TEXT,
    direcao        VARCHAR(10),
    data_interacao TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS enderecos_proponente (
    endereco_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proponente_id      BIGINT       NOT NULL,
    cep                VARCHAR(8)   NOT NULL,
    tipo_logradouro    tipo_logradouro_enum DEFAULT 'RUA',
    logradouro         VARCHAR(255) NOT NULL,
    numero             VARCHAR(20)  NOT NULL,
    complemento        VARCHAR(100),
    bairro             VARCHAR(100) NOT NULL,
    cidade             VARCHAR(100) NOT NULL,
    uf                 uf_enum      DEFAULT 'SP',
    principal          BOOLEAN      DEFAULT FALSE,
    criado_em          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    ultima_atualizacao TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS links_uteis (
    link_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo        VARCHAR(100) NOT NULL,
    url           TEXT         NOT NULL,
    descricao     VARCHAR(255),
    categoria     categoria_link_enum DEFAULT 'OUTROS',
    tipo_convenio tipo_convenio_enum,
    tags_busca    VARCHAR(255),
    criado_em     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
