name: Publicar Release Automática

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest # 🚀 Máquina Windows nativa no servidor do GitHub
    permissions:
      contents: write

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v4

    - name: Configurar o Java 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven

    - name: Compilar, Empacotar e Gerar Executável (.jar + .exe)
      run: mvn clean package -DskipTests # Remove o './' pois o Windows não usa shell script

    - name: Criar Release e Upload dos Artefatos
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/*.jar
          target/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}